project:
  name: cubee-api-server

image:
  repository: gocreating/cubee-api-server
  # repository: docker.io/gocreating/cubee-api-server
  tag: ${IMAGE_TAG}

pod:
  labels:
    env: "stg"
    cluster: "cubee-stg"

healthz:
  path: /
  initialDelay: 15
  period: 15
  timeout: 10
  success: 1
  failure: 3

autoScaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
