project:
  name: cubee-api-server

image:
  repository: gocreating/cubee-api-server
  tag: ${IMAGE_TAG}

pod:
  labels:
    env: "stg"
    cluster: "cubee-stg"

healthz:
  path: /
  initialDelay: 15
  period: 15
  timeout: 10
  success: 1
  failure: 3

autoScaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  rules:
    # can redirect cubee.cc, mutate with next rule
    - host: stg.cubee.cc
      http:
        paths:
        - path: /
          backend:
            serviceName: cubee-api-server
            servicePort: 8000

    # can redirect <any-sub-domain>.cubee.cc, mutate with previous rule
    # - host: www.cubee.cc
    #   http:
    #     paths:
    #     - path: /*
    #       backend:
    #         serviceName: cubee-api-server
    #         servicePort: 8000

    - host: api.stg.cubee.cc
      http:
        paths:
        - path: /
          backend:
            serviceName: cubee-api-server
            servicePort: 8000
