project:
  name: cubee-api-server

image:
  repository: gocreating/cubee-api-server
  tag: release-${CIRCLE_SHA1}

pod:
  labels:
    env: "prod"
    cluster: "cubee-production"

healthz:
  path: /
  initialDelay: 15
  period: 15
  timeout: 10
  success: 1
  failure: 3
