project:
  name: cubee-api-server

image:
  repository: gocreating/cubee-api-server
  tag: ${IMAGE_TAG}

pod:
  labels:
    env: "prod"
    cluster: "cubee-prod"

healthz:
  path: /info
  initialDelay: 300
  period: 600
  timeout: 10
  success: 1
  failure: 3

autoScaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

ingress:
  rules:
    - host: api.cubee.cc
      http:
        paths:
        - path: /
          backend:
            serviceName: cubee-api-server
            servicePort: 8000
