version: '3'
services:
  api-server:
    build: .
    ports:
      # external port: internal port
      - "8000:8000"
    volumes:
      - .:/srv/cubee-api-server
      - ./config-prod.yaml:/etc/config.yaml
    environment:
      - FLASK_APP=app
