version: '3'
services:
  api-server:
    build: .
    ports:
      # external port: internal port
      - "8000:5000"
    volumes:
      - .:/srv/cubee-api-server
      - ./config-stg.yaml:/etc/config.yaml
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
    entrypoint: flask
    command: "run --host=0.0.0.0"
