apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${PROJECT_NAME}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress-prod"
spec:
  rules:
  - host: api.cubee.cc
    http:
      paths:
      - backend:
          serviceName: ${PROJECT_NAME}
          servicePort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}
spec:
  selector:
    app: ${PROJECT_NAME}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
      - name: ${PROJECT_NAME}
        image: gocreating/cubee-api-server:release-${CIRCLE_SHA1}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
