"""migration 20200104v1

Revision ID: 342a10305d8b
Revises:
Create Date: 2020-01-04 01:00:07.956891

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '342a10305d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='body::json')
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('posts', 'body',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
