"""migration 20200104v3

Revision ID: be99bdb3cff7
Revises: 83e85ccd5bd8
Create Date: 2020-01-04 20:31:27.762402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be99bdb3cff7'
down_revision = '83e85ccd5bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    # ### end Alembic commands ###
