apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.project.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: cubee-cc-tls
      hosts:
        - cubee.cc
        - "*.cubee.cc"
  rules:
  # can redirect cubee.cc, mutate with next rule
  - host: cubee.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.project.name }}
          servicePort: 8000

  # can redirect <any-sub-domain>.cubee.cc, mutate with previous rule
  # - host: www.cubee.cc
  #   http:
  #     paths:
  #     - path: /*
  #       backend:
  #         serviceName: {{ .Values.project.name }}
  #         servicePort: 8000

  - host: "*.cubee.cc"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.project.name }}
          servicePort: 8000
