kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.project.name }}
spec:
  selector:
    app: {{ .Values.project.name }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
